#!/usr/bin/env bash
echo --------------------------------------------------------------------
# convert to MAX 512px in either dimension
echo --Thumbnailifying $1 with basename ${1%.*}

echo --------------------------------------------------------------------

echo --Image size is $(php -r "\$size=getimagesize(\$argv[1]);echo max(\$size[0], \$size[1]);" $1)

if [ $(php -r "\$size=getimagesize(\$argv[1]);echo max(\$size[0], \$size[1]);" $1) -lt 150 ]; then
	echo ----Image too small to thumbnail \(pixel art\).  Exiting.
	exit
fi

echo --Creating JPEG
if [ ${1: -4} == ".gif" ]; then
	echo --Input is a GIF, we can\'t do shit
else
	echo --Input is NOT a GIF\; JPEG-ifying the entire file

	echo ----convert -verbose "$1" -auto-orient -background white -alpha remove -quality 75 -resize 512x512\> "${1%.*}_thumb.jpg"
	convert -verbose "$1" -auto-orient -background white -alpha remove -quality 75 -resize 512x512\> "${1%.*}_thumb.jpg"

	echo --Creating temporary holder for losslessly compressed output file as _tmp.png

	# PNG is lossless by default
	echo ----convert -verbose "$1" -auto-orient -resize 512x512\> "${1%.*}_tmp.png"
	convert -verbose "$1" -auto-orient -resize 512x512\> "${1%.*}_tmp.png"
fi

echo --Creating lossy WebP
if [ ${1: -4} == ".gif" ]; then
	echo --Input is a GIF\; WebP for gifs is...poor.  Not creating a WebP
else
	echo --Input is NOT a GIF\; invoking cwebp

	echo ----Creating lossy static WebP
	echo ------cwebp -v -mt -m 6 -pass 10 -quiet -metadata none "${1%.*}_tmp.png" -o "${1%.*}_thumb.webp"
	cwebp -v -mt -m 6 -pass 10 -quiet -metadata none "${1%.*}_tmp.png" -o "${1%.*}_thumb.webp"
fi

echo --Removing temporary lossless image
echo ----rm "${1%.*}_tmp.png"
rm "${1%.*}_tmp.png"

echo Done with $1!
echo --------------------------------------------------------------------
