#!/bin/bash

# --defaults-file Auth file created for this backup
# -i Write additional information in the dump file such as program version, server version, and host.
# -c Use complete INSERT statements that include column names.
# -B Dump several databases. Normally, mysqldump treats the first name argument on the command line as a database name and following names as table names. With this option, it treats all name arguments as database names. CREATE DATABASE and USE statements are included in the output before each new database.
# --default-character-set Character set to use
# --order-by-primary Sorts each table's rows by primary key, or first unique key, if such a key exists
# -Q Quote identifiers (such as database, table, and column names) within backtick (`) characters.
# -r Output file
# --skip-extended-insert Keep separate rows in separate inserts
mysqldump --defaults-file=$1 -i -c -B --default-character-set=utf8mb4 --order-by-primary -Q -r $BACKUP_DIR"database.sql" --skip-extended-insert
